<?php

class Reset extends User
{

    public $new_password;

    public function tableName()
    {
        return parent::tableName();
    }

    public function rules()
    {
        return array(
            array('email', 'required'),
            array('email', 'email'),
            array('email', 'notExist'),
           // array('email, status, password', 'safe')
        );
    }

    public function attributeLabels()
    {
        return array(
            'email'=>Yii::t('main','Адрес электронной почты ')
        );
    }

    public function notExist($attribute, $params)
    {
        if(!$model = User::model()->find('email = :email',[':email'=>$this->email]))
        {
            $this->addError($attribute, Yii::t('main','Пользователя с таким Email не найден !'));
        }else{
            if($model->status == User::STATUS_NOT_AUTHORIZED){
                $this->addError($attribute, Yii::t('main','Ваш аккаунт не авторизирован!
                    На Ваш e-mail (который вы ввели при регистрации) было отправлено письмо с ссылкой для подтверждение регистрации,
                    а так же инструкции по дальнейшей работе с ресурсом. В случае если вы не получили письмо - проверьте папку со спамом.'));
            }
            if($model->status == User::STATUS_BLOCKED){
                $this->addError($attribute, Yii::t('main','Ваш аккаунт заблокирован!'));
            }
        }

    }


    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }
}